name: Linux install

on: [push]

env:
  SINTEF_REFERENCE: "android-cmdline-tools*"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True

jobs:
  conan-install-linux:
    name: Conan
    runs-on: ubuntu-20.04
    container:
      image: conanio/gcc8
      options: -u 0
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install conan requests
      - name: Configure Conan
        run: |
          conan remote add sintef ${CONAN_UPLOAD} --insert 1
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      - name: Conan create
        run: |
          conan create \
            --build missing \
            --build outdated \
            --build android_ndk_installer \
            -s os=Android \
            -s os_build=Linux \
            -s os.api_level=28 \
            -s arch_build=x86_64 \
            -s compiler=clang \
            -s compiler.version=9 \
            -s compiler.libcxx=c++_shared \
            . joakimono/testing
      - name: Conan upload
        run: |
          conan upload -c -r sintef ${SINTEF_REFERENCE} --retry 5 --retry-wait 20 --force
